Shooping/Shooping/Controllers/CitiesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shooping.Data;
using Shooping.Data.Entities;
using Shooping.Models;

namespace Shooping.Controllers;
public class CitiesController : Controller
{

    private readonly DataContext _context;

    public CitiesController(DataContext context)
    {
        _context = context;
    }

    //public IActionResult Index()
    //{
    //    return View();
    //}




    public async Task<IActionResult> Create(int? id)
    {
        if (id is null)
        {
            return NotFound();
        }

        State? state = await _context.States.FindAsync(id);
        if (state is null)
        {
            return NotFound();
        }


        //StateViewModel model = new()
        //{
        //    CountryId = country.Id
        //};

        //City city = new()
        //{
        //    StateId = state.Id
        //};


        City city = new() { StateId = state.Id };

        return View(city);
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    //public async Task<IActionResult> Create([Bind("Id,Name")] Country country)
    public async Task<IActionResult> Create(City city)
    {
        if (ModelState.IsValid)
        {
            try
            {
                //State state = new()
                //{
                //    Cities = new List<City>(),
                //    //Country = await _context.Countries.FindAsync(model.CountryId),
                //    CountryId = model.CountryId,
                //    Name = model.Name
                //};


                ////esto se se debe a que hay un campo denominado CountryId y como finaliza con Id,
                ////tambien le da su valor a Id automaticamiente, asi que le pongo 0 ya que vamos a crearlo.
                ////esto solo pasa cuando el Id no tiene valor (osea tiene el valor) por ser un reg nuevo.
                city.Id = 0;
                ////PERO CUANDO UTILIZO UN VM QUE TIENE LA CLASE, SI DEJA EL ID A CERO (que no es el caso)

                _context.Add(city);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Shooping.Controllers.StatesController.Details),
                    "States", new { id = city.StateId });
            }
            catch (DbUpdateException dbUpdateException)
            {
                string messageError = dbUpdateException.InnerException!.Message;
                if (messageError.Contains("duplicate") || messageError.Contains("duplicada"))
                {
                    ModelState.AddModelError(string.Empty, "Ya existe una ciudad con el mismo nombre en este Deparatamento/Estado.");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                }
            }
            catch (Exception exception)
            {
                ModelState.AddModelError(string.Empty, exception.Message);
            }
        }
        return View(city);
    }





    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null || _context.Countries == null)
        {
            return NotFound();
        }

        //var state = await _context.States.Include(p => p.Country).FirstOrDefaultAsync(s => s.Id == id);
        var city = await _context.Cities.FindAsync(id);

        if (city == null)
        {
            return NotFound();
        }

        //StateViewModel model = new()
        //{
        //    //CountryId = state.Country.Id, //si hacemos el Include
        //    CountryId = state.CountryId,
        //    Id = state.Id,
        //    Name = state.Name
        //};


        return View(city);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    //public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Country country)
    public async Task<IActionResult> Edit(int id, City city)
    {
        if (id != city.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                //State state = new()
                //{
                //    Id = model.Id,
                //    Name= model.Name,
                //    CountryId = model.CountryId,
                //};

                _context.Update(city);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Shooping.Controllers.StatesController.Details), "States", new { Id = city.StateId });
            }
            catch (DbUpdateConcurrencyException)
            {
                ModelState.AddModelError(string.Empty, "No se ha podido modificar el registro.");
            }
            catch (DbUpdateException dbUpdateException)
            {
                string messageError = dbUpdateException.InnerException!.Message;
                if (messageError.Contains("duplicate") || messageError.Contains("duplicada"))
                {
                    ModelState.AddModelError(string.Empty, "Ya existe una ciudad con el mismo nombre en este departamento/estado.");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                }
            }
            catch (Exception exception)
            {
                ModelState.AddModelError(string.Empty, exception.Message);
            }

        }
        return View(city);
    }




    // GET: cities/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null || _context.Cities == null)
        {
            return NotFound();
        }

        var city = await _context.Cities.FindAsync(id);
        if (city == null)
        {
            return NotFound();
        }


        return View(city);
    }







    // GET: cites/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null || _context.Cities == null)
        {
            return NotFound();
        }

        var city = await _context.Cities.FindAsync(id);
        if (city == null)
        {
            return NotFound();
        }

        return View(city);
    }

    // POST: cites/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        if (_context.Cities == null)
        {
            return Problem("Entity set 'DataContext.Cities'  is null.");
        }
        var city = await _context.Cities.FindAsync(id);
        if (city != null)
        {
            _context.Cities.Remove(city);
        }

        await _context.SaveChangesAsync();
        return RedirectToAction("Details", "States", new { Id = city!.StateId });
    }









}

Shooping/Shooping/Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Shooping.Data;
using Shooping.Data.Entities;
using Shooping.Models;

namespace Shooping.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CountriesController : Controller
    {
        private readonly DataContext _context;

        public CountriesController(DataContext context)
        {
            _context = context;
        }



        // GET: Countries
        public async Task<IActionResult> Index()
        {
              return _context.Countries != null ? 
                     View( await _context.Countries.Include(c => c.States).ToListAsync()) 
                     : Problem("Entity set 'DataContext.Countries'  is null.");

       //     return _context.Countries != null ?
       //View(new CountryVm() { countries = await _context.Countries.Include(c => c.States).ToListAsync() })
       //: Problem("Entity set 'DataContext.Countries'  is null.");
        }



        // GET: Countries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Countries == null)
            {
                return NotFound();
            }

            var country = await _context.Countries.Include(c => c.States)!.ThenInclude(s => s.Cities)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }



        // GET: Countries/Create
        public IActionResult Create()
        {
            ////Puse la lista de Country como nulleable en en la clase de Country y con eso no hace falta esto.
            //Country country = new() { States = new List<State>() };
            //return View(country);

            return View();
        }

        // POST: Countries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Id,Name")] Country country)
        public async Task<IActionResult> Create(Country country)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(country);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException dbUpdateException)
                {
                    string messageError = dbUpdateException.InnerException!.Message;
                    if (messageError.Contains("duplicate") || messageError.Contains("duplicada"))
                    {
                        ModelState.AddModelError(string.Empty, "Ya existe un país con el mismo nombre.");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                    }
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }
            }
            return View(country);
        }






        // GET: Countries/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Countries == null)
            {
                return NotFound();
            }

            var country = await _context.Countries.FindAsync(id);
            //como su lista de States es nuleable no es necesario buscar los estados de este pais, por eso es bueno 
            //las litas y objetos de relaciones de entity framework dejarjos nuleables con el simpbolo de pregunta ?

            if (country == null)
            {
                return NotFound();
            }
            return View(country);
        }

        // POST: Countries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Country country)
        public async Task<IActionResult> Edit(int id, Country country)
        {
            if (id != country.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(country);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    ModelState.AddModelError(string.Empty, "No se ha podido modificar el registro.");
                }
                catch (DbUpdateException dbUpdateException)
                {
                    string messageError = dbUpdateException.InnerException!.Message;
                    if (messageError.Contains("duplicate") || messageError.Contains("duplicada"))
                    {
                        ModelState.AddModelError(string.Empty, "Ya existe un país con el mismo nombre.");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                    }
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }

            }
            return View(country);
        }









        // GET: Countries/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Countries == null)
            {
                return NotFound();
            }

            var country = await _context.Countries.Include(c => c.States).FirstOrDefaultAsync(c=> c.Id == id);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }

        // POST: Countries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Countries == null)
            {
                return Problem("Entity set 'DataContext.Countries'  is null.");
            }
            var country = await _context.Countries.FindAsync(id);
            if (country != null)
            {
                _context.Countries.Remove(country);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //private bool CountryExists(int id)
        //{
        //  return (_context.Countries?.Any(e => e.Id == id)).GetValueOrDefault();
        //}
    }
}

Shooping/Shooping/Views/States/Create.cshtml
@model Shooping.Data.Entities.State
@*@model Shooping.Models.StateViewModel*@

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>

<h4>Departamento/Estado</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="CountryId" />
            <partial name="_CreateEdit" />

            <div class="form-group mt-2">
                <input type="submit" value="Crear" class="btn btn-outline-primary" />
                <a asp-controller="Countries" asp-action="Details" asp-route-id="@Model.CountryId" class="btn btn-outline-success">Regresar</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Shooping/Shooping/Views/States/Delete.cshtml
@model Shooping.Data.Entities.State

@{
    ViewData["Title"] = "Delete";
}

<h1>Borrar</h1>

<h3>¿Estas seguro de querer borrar?</h3>

<partial name="_DetailsDelete" />

<div>    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Borrar" class="btn btn-outline-danger" /> 
        <a asp-controller="Countries" asp-action="Details" asp-route-id="@Model.CountryId" class="btn btn-outline-success">Regresar</a>
    </form>
</div>

Shooping/Shooping/Views/States/Details.cshtml
@model Shooping.Data.Entities.State

@{
    ViewData["Title"] = "Details";
}

<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />

<h1>Detalles</h1>


<partial name="_DetailsDelete" />

<div>
    <a asp-controller="Cities" asp-action="Create" asp-route-id="@Model.Id" class="btn btn-outline-primary">Agregar Ciudad</a>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-outline-warning">Editar Departemento/Estado</a>
    <a asp-controller="Countries" asp-action="Details" asp-route-id="@Model.CountryId" class="btn btn-outline-success">Regresar</a>
</div>
<hr />



<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Ciudades</h3>
            </div>
            <div class="panel-body">
                <table class="table table-hover table-responsive table-striped" id="MyTable">

                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Cities!.FirstOrDefault()!.Name)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Cities!)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    <a asp-controller="Cities" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-warning"><i class="fa-solid fa-pen-to-square"></i></a>
                                    <a asp-controller="Cities" asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-info"><i class="fa-solid fa-circle-info"></i></a>
                                    <a asp-controller="Cities" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger"><i class="fa-solid fa-trash"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#MyTable').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                "aLengthMenu": [
                    [25, 50, 100, 200, -1],
                    [25, 50, 100, 200, "Todos"]
                ]
            });
        });
    </script>
}

Shooping/Shooping/Views/States/Edit.cshtml
@model Shooping.Data.Entities.State
@*@model Shooping.Models.StateViewModel*@

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Departamento/Estado
</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="CountryId" />

            <partial name="_CreateEdit" />

            <div class="form-group mt-2">
                <input type="submit" value="Guardar" class="btn btn-outline-primary" />
                <a asp-controller="Countries" asp-action="Details" asp-route-id="@Model.CountryId" class="btn btn-outline-success">Regresar</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Shooping/Shooping/Views/States/_CreateEdit.cshtml
@model Shooping.Data.Entities.State

<div class="form-group">
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>

Shooping/Shooping/Views/States/_DetailsDelete.cshtml
@model Shooping.Data.Entities.State

<div>
    <h4>País</h4>
    <hr />
    <dl class="Departamento/Estado">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CitiesNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CitiesNumber)
        </dd>
    </dl>
</div>